; =====================================================================
; VEYRA Inno Setup Installer Script
; Stage 8 Packaging, Deployment & Windows Release Engineering
; =====================================================================

#define MyAppName "VEYRA"
#define MyAppVersion "0.1.0"
#define MyAppPublisher "VEYRA Team"
#define MyAppExeName "VEYRA.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".veyra"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; Basic Application Information
AppId={{9C0276A6-0F39-4C93-B2A5-8F4AC07E187F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=..\dist\installer
OutputBaseFilename=VEYRA_Setup_v{#MyAppVersion}
SetupIconFile=..\assets\branding\normal\VEYRA_Normal_Icon.ico
UninstallDisplayIcon={app}\{#MyAppExeName}

; Compression & Architecture
Compression=lzma2/ultra
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64compatible
WizardStyle=modern

; Least Privilege Security: Installs per-user without requiring UAC elevation by default
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

; Safety & Overwrite Controls
DisableProgramGroupPage=yes
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Standalone application bundle files generated by PyInstaller
Source: "..\dist\VEYRA\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\branding\normal\VEYRA_Normal_Icon.ico"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\assets\branding\normal\VEYRA_Normal_Icon.ico"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Clean up temporary cache or runtime socket files, but preserve %LOCALAPPDATA%\VEYRA history
Type: files; Name: "{app}\*.log"
Type: files; Name: "{app}\*.tmp"
